import fs from 'node:fs';
const root=fs.existsSync('dist/index.html')?'dist':'.';
const data=fs.readFileSync(`${root}/demo.js`,'utf8').replace(/^export /gm,'');
const app=fs.readFileSync(`${root}/app.js`,'utf8').replace(/^import[^\n]+\n/,'');
const requirements=fs.readFileSync(`${root}/requirements.json`,'utf8');
fs.writeFileSync(`${root}/bundle.js`,`// Generated by build.mjs. Supports file:// and static hosting.\n(()=>{\nconst BUNDLED_REQUIREMENTS=${requirements};\n${data}\n${app}\n})();\n`);
console.log('Built standalone browser bundle with embedded requirements.');
